export const CATEGORIES: string[] = [
    'mmorpg',
    'shooter',
    'strategy',
    'moba',
    'racing',
    'sports',
    'social',
    'sandbox',
    'open-world',
    'survival',
    'pvp',
    'pve',
    'pixel',
    'voxel',
    'zombie',
    'turn-based',
    'first-person',
    'third-Person',
    'top-down',
    'tank',
    'space',
    'sailing',
    'side-scroller',
    'superhero',
    'permadeath',
    'card',
    'battle-royale',
    'mmo',
    'mmofps',
    'mmotps',
    '3d',
    '2d',
    'anime',
    'fantasy',
    'sci-fi',
    'fighting',
    'action-rpg',
    'action',
    'military',
    'martial-arts',
    'flight',
    'low-spec',
    'tower-defense',
    'horror',
    'mmorts'
]

export const SORT_OPTIONS = [
    {value: "relevance", label: 'По релевантности'},
    {value: 'alphabetical', label: 'По алфавиту'},
    {value: 'popularity', label: 'По популярности'},
    {value: 'release_date', label: 'Дата релиза'},
]

export const PLATFORM_OPTIONS = [
    {value: "all", label: 'Все платформы'},
    {value: 'pc', label: 'ПК'},
    {value: 'browser', label: 'Браузер'},
]